name: Set Up Reliable Terraform bcknd Backend for Infrastructure Management
'on':
  workflow_run:
    workflows: ["Establish Federated Identity Credentials"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: Deploy TF bcknd to backend
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        run: |
          set -a
          source terraform-dev.tfvars
          az group create \
            -l $bcknd_location \
            -n $bcknd_resource_group_name

      - name: Create Storage Account
        run: |
          set -a
          source terraform-dev.tfvars
          az storage account create \
            -n $bcknd_storage_account_name \
            -g $bcknd_resource_group_name \
            -l $TF_VAR_location \
            --sku Standard_LRS \
            --allow-blob-public-access false

      - name: Create STG Container
        run: |
          set -a
          source terraform-dev.tfvars
          az storage container create \
            --name $bcknd_container_name \
            --account-name $bcknd_storage_account_name