name: Deploy Azure Infrastructure On Dev
'on':
  workflow_run:
    workflows: ["Set Up Reliable Terraform State Backend for Infrastructure Management"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: Deploy TF State to backend
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: latest

      - name: Terraform init
        id: init
        run: terraform init -no-color

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve tfplan