name: Establish Federated Identity Credentials for Secure Authentication
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/environments/dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: latest

      - name: Az login
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Check Terraform Formatting
        run: terraform fmt -check

      - name: Validate Terraform Code
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Show version
        run: tflint --version

      - name: Run TFLint
        run: tflint -f compact

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v1
        with:
          directory: ./infrastructure/environments/dev

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Apply FIC Configuration
        run: terraform apply -auto-approve